Labtask/Labtask/Models/Database/Database.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.SqlClient;

namespace Labtask.Models.Database
{
    public class Database
    {
        public Students Student { get; set; }

        public Database()
        {
            string connString = @"Server=DESKTOP-PH1NG8J;Database=CrudO;Integrated Security=true;";
            SqlConnection conn = new SqlConnection(connString);

            Student = new Students(conn);

        }
    }
}

Labtask/Labtask/Models/Database/Students.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;


namespace Labtask.Models.Database
{
    public class Students
    {
        SqlConnection conn;

        public Students(SqlConnection conn)
        {
            this.conn = conn;
        }

        public void Insert(Student s)
        {
            string query = String.Format("Insert into student values ('{0}','{1}','{2}',{3},'{4}',{5})", s.Name, s.Id,s.DOB,s.Credit,s.CGPA,s.deptId);
            SqlCommand cmd = new SqlCommand(query, conn);
            conn.Open();
            cmd.ExecuteNonQuery();
            conn.Close();
        }

        public List<Student> GetAll()
        {
            List<Student> students = new List<Student>();
            string query = "select * from student";
            SqlCommand cmd = new SqlCommand(query, conn);
            conn.Open();
            SqlDataReader reader = cmd.ExecuteReader();
            while(reader.Read())
            {
                Student s = new Student()
                {
                    Name= reader.GetString(reader.GetOrdinal("Name")),
                    Id = reader.GetString(reader.GetOrdinal("Id")),
                    DOB = reader.GetString(reader.GetOrdinal("DOB")),
                    Credit = reader.GetInt32(reader.GetOrdinal("Credit")),
                    CGPA = reader.GetString(reader.GetOrdinal("CGPA")),
                    deptId = reader.GetInt32(reader.GetOrdinal("deptId")),

                };
                students.Add(s);


            }
            conn.Close();
            return students;

        }

       public Student Get(string Id)
        {
            Student s = null;
            string query = $"select * from student where id= '{Id}'";
            SqlCommand cmd = new SqlCommand(query, conn);
            conn.Open();
            SqlDataReader reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                s = new Student()
                {
                    Name = reader.GetString(reader.GetOrdinal("Name")),
                    Id = reader.GetString(reader.GetOrdinal("Id")),
                    DOB = reader.GetString(reader.GetOrdinal("DOB")),
                    Credit = reader.GetInt32(reader.GetOrdinal("Credit")),
                    CGPA = reader.GetString(reader.GetOrdinal("CGPA")),
                    deptId = reader.GetInt32(reader.GetOrdinal("deptId")),

                };
               
                


            }
            conn.Close();
            return s;


        }

        public void Update(Student s)
        {
            string query = $"Update student Set Name='{s.Name}', DOB='{s.DOB}' , Credit={s.Credit}, CGPA='{s.CGPA}', DeptId='{s.deptId}' Where Id = '{s.Id}'";
            SqlCommand cmd = new SqlCommand(query, conn);
            conn.Open();
            cmd.ExecuteNonQuery();
            conn.Close();
        }

        public void Delete(string s)
        {
            string query = $"Delete from student Where Id = '{s}'";
            SqlCommand cmd = new SqlCommand(query, conn);
            conn.Open();
            cmd.ExecuteNonQuery();
            conn.Close();
        }

        public Student LogIn(string s)
        {

            Student a = null;
            string query = $"select * from Admin where UserName= '{s}'";
            SqlCommand cmd = new SqlCommand(query, conn);
            conn.Open();
            SqlDataReader reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                a = new Student()
                {
                    UserName = reader.GetString(reader.GetOrdinal("UserName")),
                    password = reader.GetString(reader.GetOrdinal("password")),
                    

                };




            }
            conn.Close();
            return a;


        }
    }
}

Labtask/Labtask/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Labtask.Models
{
    public class Student
    {
        [Required]

        public string Name { get; set; }
        [Required]
        public string Id { get; set; }
        [Required]
        public string DOB { get; set; }
        [Required]
        public int Credit { get; set; }
        [Required]

        public string CGPA { get; set; }
        [Required]

        public int deptId { get; set; }

        public string UserName { get; set; }
        public string password { get; set; }
    }
}

Labtask/Labtask/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Labtask.Controllers;
using Labtask.Models;
using Labtask.Models.Database;

namespace Labtask.Controllers
{
    public class StudentController : Controller
    {
        public ActionResult Create()
        {
            Student s = new Student();
            return View(s);
        }

        [HttpPost]

        public ActionResult Create(Student s)
        {
            if (ModelState.IsValid)
            {
                Database d = new Database();
                d.Student.Insert(s);
                return RedirectToAction("AllStudent");

            }
            return View();
            
        }

        public ActionResult AllStudent()
        {
            Database db = new Database();
            var student= db.Student.GetAll();

            return View(student);
        }

        public ActionResult Edit(string Id)
        {
            Database db = new Database();
            var s = db.Student.Get(Id);
           

            return View(s);
        }

        [HttpPost]

        public ActionResult Edit(Student s)
        {
            Database d = new Database();
            d.Student.Update(s);
            return RedirectToAction("AllStudent");
        }

        public ActionResult Delete(string Id)
        {
            Database d = new Database();
            d.Student.Delete(Id);
            return RedirectToAction("AllStudent");
        }

        public ActionResult Login()
         {
             Student s = new Student();
             return View(s);
         } 
        [HttpPost]
        public ActionResult Login(Student s)
        {
            Database d = new Database();
            var a= d.Student.LogIn(s.UserName);
            if (a.UserName==s.UserName && a.password==s.password)
            {
                return RedirectToAction("AllStudent");
            }
            else
                return RedirectToAction("Create");


        }

    }
}

Labtask/Labtask/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Labtask/Labtask/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Labtask/Labtask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Just Crud Operations", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Create", "Create", "Student")</li>
                    <li>@Html.ActionLink("Show All Student", "AllStudent", "Student")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Labtask/Labtask/Views/Student/AllStudent.cshtml
@{
    ViewBag.Title = "AllStudent";
}
@model List<Labtask.Models.Student>

<div class="container">
    <table class="table table-condensed">
        <tr>
            <th>Name</th>
            <th>Id</th>
            <th>Date of Birth</th>
            <th>Credit</th>
            <th>CGPA</th>
            <th>DEPTNO</th>
            <th></th>
            <th></th>
        </tr>
        @foreach (var student in @Model)
        {
    <tr>
        <td>@student.Name</td>
        <td>@student.Id</td>
        <td>@student.DOB</td>
        <td>@student.Credit</td>
        <td>@student.CGPA</td>
        <td>@student.deptId</td>
        <td><a class="btn btn-success" href="/Student/Edit/@student.Id">Edit</a></td>
        <td><a class="btn btn-danger" href="/Student/Delete/@student.Id">Delete</a></td>
    </tr>
        }

    </table>
</div>

Labtask/Labtask/Views/Student/Create.cshtml
@model Labtask.Models.Student
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<div>
    <form action="/Student/Create" method="post">

        <input type="text" name="Name" class="form-control" placeholder="Name" />
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        <br />
        <input type="text" name="Id" class="form-control" placeholder="Id" />
        @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
        <br />
        <input type="text" name="DOB" class="form-control" placeholder="Date Of Birth" />
        @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
        <br />
        <input type="text" name="Credit" class="form-control" placeholder="Credits" />
        @Html.ValidationMessageFor(model => model.Credit, "", new { @class = "text-danger" })
        <br />
        <input type="text" name="CGPA" class="form-control" placeholder="CGPA" />
        @Html.ValidationMessageFor(model => model.CGPA, "", new { @class = "text-danger" })
        <br />
        <input type="text" name="DeptId" class="form-control" placeholder="Department" />
        @Html.ValidationMessageFor(model => model.deptId, "", new { @class = "text-danger" })
        <br />
        <input type="submit" class="btn btn-block" value="Submit" />

    </form>
</div>

Labtask/Labtask/Views/Student/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}
@model Labtask.Models.Student

<div>
    <form action="" method="post">
        <br />
        <p>Name</p>
        <input type="text" name="Name" value="@Model.Name" class="form-control" placeholder="Name" />
        <br />
        <p>Id</p>
        <input type="text" name="Id" value="@Model.Id" class="form-control" placeholder="Id" />
        <br />

        <p>Date of Birth</p>
        <input type="text" name="DOB" value="@Model.DOB" class="form-control" placeholder="Date Of Birth" />
        <br />
        <p>Credit</p>
        <input type="text" name="Credit" value="@Model.Credit" class="form-control" placeholder="Credits" />
        <br />
        <p>CGPA</p>
        <input type="text" name="CGPA" value="@Model.CGPA" class="form-control" placeholder="CGPA" />
        <br />
        <p>Department</p>
        <input type="text" name="DeptId" value="@Model.deptId" class="form-control" placeholder="Department" />
        <br />
        <input type="submit" class="btn btn-block" value="Submit" />

    </form>
</div>

Labtask/Labtask/Views/Student/Login.cshtml
@model Labtask.Models.Student 
@{
    ViewBag.Title = "Login";
}

<div>
    <form action="/Student/Login" method="post">
        <br />

        <input type="text" name="UserName" class="form-control" placeholder="Name" />

        <br />
        <input type="text" name="password" class="form-control" placeholder="Id" />

        <br />

        <input type="submit" class="btn btn-block" value="Submit" />

    </form>
</div>